### ISSUE TITLE
no RUNTIME DESTINATION for executable target "cbmconvert"

### ISSUE THREAD

**Issue by Marrin** [dr-m/cbmconvert#2]
The step with `cmake ..` lead to the following error for me:

```
$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:57 (INSTALL):
  INSTALL TARGETS given no RUNTIME DESTINATION for executable target
  "cbmconvert".
```

I fixed this by adding the RUNTIME DESTINATION this was:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 218a831..8cd267e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -54,7 +54,10 @@ ELSE()
   INSTALL(FILES cbmconvert.1 zip2disk.1 disk2zip.1
     DESTINATION ${CMAKE_INSTALL_MANDIR}/man1)
 ENDIF()
-INSTALL(TARGETS cbmconvert zip2disk disk2zip)
+INSTALL(
+  TARGETS cbmconvert zip2disk disk2zip
+  RUNTIME DESTINATION bin
+)
 
 ENABLE_TESTING()
 ADD_TEST (cbmconvert_usage ${CMAKE_BINARY_DIR}/cbmconvert)
```

Then it compiled.

**Comment by dr-m** [comment]
Thank you! Which version of `cmake` are you using?

**Comment by Marrin** [comment]
Version 3.10.2.  I know, somewhat ancient, but the CMakeList.txt says the minimum required version is 3.0.2.  If the old version is the cause, then maybe the fix is bumping up that minimum required version and me upgrading the tool chain. 🙂

**Comment by dr-m** [comment]
Thank you. I try to support as old tools as technically possible, in case someone wants to use this on an older system where a newer tool chain might not be available at all.

I see that according to the [documentation](https://cmake.org/cmake/help/v3.0/command/install.html), already CMake 3.0.2 should support the `RUNTIME DESTINATION` attribute, so no version check should be needed. For some reason, this was not flagged by newer versions of CMake that I am using (currently 3.24.2).
